### ISSUE TITLE
Error at multipart/form-data on Oracle Linux Server release 7.5

### ISSUE THREAD

**Issue by florin-ctu** [ColasNahaboo/cgibashopts#8] opened 2023-01-08 09:46 UTC
[version 4.1.1]

# tests/tewiba -v
== Sourcing __INIT__
== Test file: filefield-runaway.test:
== file field then text field
***TEST ERROR file field then text field*** rest of params gobbled: 1,5d0
< Content-Disposition: form-data; name="foo"
<
< bar
< -----------------------------234854398038784223431883737325--
<
***ERRORS:1
== Test file: form-files.test:
== Form file upload from browser CBOgenf-Chromium62linux
== Form file upload from browser CBOgenf-ff57linux
== Form file upload from browser CBOgenf-ff57W10
== Form file upload from browser CBOgenf-GoogleChrome62W10
== Form file upload from browser CBOgenf-MicrosoftEdge40W10
***TEST ERROR Form file upload from browser CBOgenf-MicrosoftEdge40W10*** file 5 differ for browser CBOgenf-MicrosoftEdge40W10. See difference from expected to result by: diff /d02/cgi-bin/tests/files-dos2/file5 /tmp/CBOgenf-MicrosoftEdge40W10-file5
== Form file upload from browser CBOgenf-WindowsPhoneLumia
***TEST ERROR Form file upload from browser CBOgenf-WindowsPhoneLumia*** file 5 differ for browser CBOgenf-WindowsPhoneLumia. See difference from expected to result by: diff /d02/cgi-bin/tests/files-dos2/file5 /tmp/CBOgenf-WindowsPhoneLumia-file5
***ERRORS:2
== Test file: form-nofiles.test:
== Form file upload from browser CBOgenf-Chromium62linux
== Form file upload from browser CBOgenf-ff57linux
== Form file upload from browser CBOgenf-ff57W10
== Form file upload from browser CBOgenf-GoogleChrome62W10
== Form file upload from browser CBOgenf-MicrosoftEdge40W10
== Form file upload from browser CBOgenf-WindowsPhoneLumia
== OK
== Test file: form.test:
== Form POST submit from browser CBOgen-Chromium62linux
== Form POST submit from browser CBOgen-ff57linux
== Form POST submit from browser CBOgen-ff57W10
== Form POST submit from browser CBOgen-GoogleChrome62W10
== Form POST submit from browser CBOgen-Microsoft
== OK
== Test file: query-string.test:
== Empty querystring
== Indexed search, legacy
== Single param
== Multiple params
== param function
== urldecode
== OK
== ***** Total tests failed: 3 *****

**Comment by ColasNahaboo** [comment] 2023-01-08 15:22
Thanks for the report!
Fixed in v4.1.2

**Comment by ColasNahaboo** [comment] 2023-01-08 15:27
Oops, I may have read too fast. This issue may be different from #9.

If it still happens with 4.1.2, Could you join the diffs mentioned in the test error reports: E.g:

> See difference from expected to result by: diff /d02/cgi-bin/tests/files-dos2/file5 /tmp/CBOgenf-MicrosoftEdge40W10-file5[...]
> See difference from expected to result by: diff /d02/cgi-bin/tests/files-dos2/file5 /tmp/CBOgenf-WindowsPhoneLumia-file5

**Comment by florin-ctu** [comment] 2023-01-08 16:55
I test using version 4.1.2 `tests/tewiba -v` on Oracle Linux Server release 7.5.
The output is unchanged from previous post.


`# ./tests/tewiba -v`
== Sourcing __INIT__
== Test file: filefield-runaway.test:
== file field then text field
***TEST ERROR file field then text field*** rest of params gobbled: 1,5d0
< Content-Disposition: form-data; name="foo"
<
< bar
< -----------------------------234854398038784223431883737325--
<
***ERRORS:1
== Test file: form-files.test:
== Form file upload from browser CBOgenf-Chromium62linux
== Form file upload from browser CBOgenf-ff57linux
== Form file upload from browser CBOgenf-ff57W10
== Form file upload from browser CBOgenf-GoogleChrome62W10
== Form file upload from browser CBOgenf-MicrosoftEdge40W10
***TEST ERROR Form file upload from browser CBOgenf-MicrosoftEdge40W10*** file 5 differ for browser CBOgenf-MicrosoftEdge40W10. See difference from expected to result by: diff /root/cgibashopts-main/tests/files-dos2/file5 /tmp/CBOgenf-MicrosoftEdge40W10-file5
== Form file upload from browser CBOgenf-WindowsPhoneLumia
***TEST ERROR Form file upload from browser CBOgenf-WindowsPhoneLumia*** file 5 differ for browser CBOgenf-WindowsPhoneLumia. See difference from expected to result by: diff /root/cgibashopts-main/tests/files-dos2/file5 /tmp/CBOgenf-WindowsPhoneLumia-file5
***ERRORS:2
== Test file: form-nofiles.test:
== Form file upload from browser CBOgenf-Chromium62linux
== Form file upload from browser CBOgenf-ff57linux
== Form file upload from browser CBOgenf-ff57W10
== Form file upload from browser CBOgenf-GoogleChrome62W10
== Form file upload from browser CBOgenf-MicrosoftEdge40W10
== Form file upload from browser CBOgenf-WindowsPhoneLumia
== OK
== Test file: form.test:
== Form POST submit from browser CBOgen-Chromium62linux
== Form POST submit from browser CBOgen-ff57linux
== Form POST submit from browser CBOgen-ff57W10
== Form POST submit from browser CBOgen-GoogleChrome62W10
== Form POST submit from browser CBOgen-Microsoft
== OK
== Test file: query-string.test:
== Empty querystring
== Indexed search, legacy
== Single param
== Multiple params
== param function
== urldecode
== OK
== ***** Total tests failed: 3 *****

diff /root/cgibashopts-main/tests/files-dos2/file5 /tmp/CBOgenf-MicrosoftEdge40W10-file5
diff: /tmp/CBOgenf-MicrosoftEdge40W10-file5: No such file or directory

diff /root/cgibashopts-main/tests/files-dos2/file5 /tmp/CBOgenf-MicrosoftEdge40W10-file-5
4c4
< 5
---
5

diff /root/cgibashopts-main/tests/files-dos2/file5 /tmp/CBOgenf-WindowsPhoneLumia-file5
diff: /tmp/CBOgenf-WindowsPhoneLumia-file5: No such file or directory

diff /root/cgibashopts-main/tests/files-dos2/file5 /tmp/CBOgenf-WindowsPhoneLumia-file-5
4c4
< 5
---
5

**Comment by ColasNahaboo** [comment] 2023-01-08 22:19
OK, I will have to install a  Oracle Linux Server release 7.5 to see what is happenning.
My main suspicion is the bash version. It seems to be bash-4.2.46 for OLS7.5 and bash-4.4.19 for OLS8.0
I will try to have a glance first if I see something there

**Comment by ColasNahaboo** [comment] 2023-01-08 22:55
OK, I can reproduce the same problem on a CentOS 7, that has a bash-4.2.46

**Comment by florin-ctu** [comment] 2023-01-09 07:00
I confirm bash version
`# bash --help`
`GNU bash, version 4.2.46(2)-release-(x86_64-redhat-linux-gnu)`

**Comment by ColasNahaboo** [comment] 2023-01-09 14:39
OK, the test suite actually detects that the bug described in issue #7 is not fixed for bash 4.2.46 (or the sed of CentOS7 / OLS7.5)
I don't know yet how/when/if I can fix it, I'll see...

In the meantime, you can use the workaround described in issue #7: in forms uploading files to OLS7.5 servers, be sure that the a file field that can be used to upload binary files is the last input field in forms, as fields after it will be ignored.

Edit: no, this is NOT the bug of #7. It is actually the code of the test itself that fails in bash 4.2, you can ignore. The test will be fixed in the next release.

**Comment by ColasNahaboo** [comment] 2023-01-10 23:24
In fact, this does not seems like a bug that could happen in real life.

The failing tests are for uploading a "monster" file. A file `tests/files-dos2/file5` that windows recognizes as a text file, but has in it carriage returns (`\r`)in the "wrong" places: (normal text file has lines terminated by \r\n, and no single \r or \n in the middle)
```1  \r   2  \r  \n   3  \n   4  \n   5  \n```
So this case should not happen in real use. It is included in the test suite to check that the code can handle weird cases.

And it seems that bash 4.2 had a bug that made it choke on these monster files, but was fixed in the more recent bash version. I could not find exactly what fails in 4.2.

So, you can ignore the test suite errors, it should work in real use.

I will include a note in the doc for this case, and see if I can make the test suite autodetect these old bash versions and not run the "monster file" test in this case.

**Comment by ColasNahaboo** [comment] 2023-01-11 06:47
Fixed in Release v4.1.3: https://github.com/ColasNahaboo/cgibashopts/releases/tag/v4.1.3

**Closed as completed by ColasNahaboo** 2023-01-11 06:47 UTC
